---
title: "Blog Article"
format: html
editor: visual
---

### [HOME](https://syoshiro.github.io/web-portfolio/Index) \| [PAST WORK](https://syoshiro.github.io/web-portfolio/Past%20Work) \| [RESUME](https://github.com/syoshiro/web-portfolio/blob/main/Sarina%20Oshiro%20Resume%202024.pdf)

\

Please find an example of a blog article I wrote in 2023. You may also find the published article, here: <https://www.wcpinst.org/our-work/digital-gallery/herpathtothehill/anna-whitwam/>

### **HER PATH TO THE HILL: Anna Whitwam\'s Career as a Legislative Correspondent and Staff Assistant  **

**HER PATH**\
Growing up in Michigan, Anna Whitwam jokes she \"had a lot of different dream jobs. It kind of changed every couple of years.\" As a kid, she wanted to be an astronaut because she was fascinated by space. In high school, Anna considered applying to college pre-med programs to become a doctor, until she met her AP Government teacher, Matt Koleszar, who piqued her interest in politics. 

When Koleszar ran for a seat in the Michigan State House in 2018, Anna, who at the time was a college student at Central University of Michigan, was invited to work on his campaign. It was this experience that offered her an \"up close and personal\" look at political work. She says the job \"reaffirmed not only my passion for what I was doing, but also that I could make this a career, that I was good at this, that this is something I could be interested in for the rest of my life."

After Koleszar was elected, Anna took a position as a legislative intern in his State House office. She began to focus on policy and gained first-hand experience \"tackling a lot of the issues that were hitting Michiganders."

After graduating from college in December 2020, Anna was offered a legislative internship in Congresswoman Breanda Lawrence\'s D.C. office (D-MI-14). In this position, she says, \"I really got to take my experience from state level politics to national politics.\"

When her internship ended in 2021, she took a full-time staffer position with Congresswoman Gwen Moore (D-WI-04), where she currently works.\

**HER JOB**

Officially holding the title \"Legislative Correspondent and Staff Assistant,\" Anna describes her professional responsibilities as a combination of the two positions. \

**Legislative Correspondent Duties** \
On the Hill, Legislative Correspondents or \"LCs\" are typically responsible for a portfolio of policy areas, for which they track related legislation, draft constituent response letters, manage constituent and interest group meetings, and advise the member on policy strategy. In Congresswoman Moore\'s office, Anna is the lead staffer for a small portfolio of animal welfare (which includes conservation policies) as well as arts, museums, culture, and religion, which \"intersect with each other.\" \

**Staff Assistant Duties**

Under her Staff Assistant duties, Anna jokes that she \"wears a lot of different hats.\" As Congresswoman Moore\'s personal assistant and driver, Anna is responsible for ensuring the Congresswoman gets to events or meetings well-prepared and on time. 

Back in the office, Anna serves as the intern coordinator, hiring, managing, and overseeing all interns throughout the year.   

Capitol Hill tours can be a big part of constituent services for Representative\'s D.C. offices, and Anna is the point of contact for \"all things tour related.\" She often delegates these tasks to the interns she supervises but remains in charge of scheduling.  

Anna also handles the office\'s mail program. She explains, \"I sort the mail, I batch the mail. I make sure that they \[constituents\] are getting the appropriate responses in an efficient manner.\" 

**THE BEST PART ABOUT HER JOB**\
Anna says her favorite part about her job is spending time with Congresswoman Moore as her personal assistant and driver. Anna describes Rep. Moore as \"easily one of the most down to Earth, funny, realistic, and genuine people that I think I\'ve ever met in my life... We have a really great relationship.\"  

\

**THE BIGGEST MISCONCEPTION ABOUT HER JOB**\
While many people seem to think Hill staffers are \"all very cutthroat people,\" Anna argues that is simply not true. In fact, she has met \"some of the most humble, genuine, hard working people\" on the Hill who are driven to serve the public. Anna says that she, like many other staffers, is eager to meet with and offer advice to interns, whether they are in her office or not. 

\

**WHAT KEEPS HER MOTIVATED AMID POLARIZATION**\
Working in a highly polarized environment like Capitol Hill can be draining, but Anna remains motivated by helping constituents get their needs met. She also finds hope for more unity in the future after working successfully and productively with colleagues across the aisle. \"Being able to find those partnerships that you can forge and use to better the lives of people across our country is a really humbling experience.\" 

\

**HER ADVICE**\
One of the biggest pieces of advice Anna has to offer is to not \"feel pressured to follow in someone\'s footsteps.\" While traditionally, Congressional staffers often follow a path from intern to staff assistant to legislative correspondent, Anna says this is \"not really the case anymore.\" She emphasizes that everyone takes a different path to the Hill and encourages aspiring professionals to \"forge your own path.\"
