---
title: "Map Example"
format: html
editor: visual
---

### [HOME](https://syoshiro.github.io/web-portfolio/Index) \| [PAST WORK](https://syoshiro.github.io/web-portfolio/Past%20Work) \| [RESUME](https://github.com/syoshiro/web-portfolio/blob/main/Sarina%20Oshiro%20Resume%202024.pdf)

# Map Deliverable

Here is an example of a map I created demonstrating \_\_\_\_\_. This map and the related analysis was developed and completed in R-studio using the MapView package.

## Map below

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tigris)
library(sf)
library(tidycensus)
library(htmltools)
library(janitor)
library(here)
library(mapview)
library(leafsync)
library(leaflet.extras2)
options(tigris_class = "sf")

census_api_key("2a6f8c21a30d3024e038d67d7d4eba647dc79cd4", overwrite =TRUE)

readRenviron("~/.Renviron")

```

I have chosen to look at California, so I am loading in my data and the variables for total population, Median income, and median age.

```{r}
#chose variables we want
myvars <- c(totalpop = "B01003_001",
            medincome = "B19013_001",
            medage = "B01002_001")

ca_counties_withgeo <- get_acs(geography = "county",
                       variables = c(myvars),
                       state = "CA",
                       output = "wide",
                       geometry = TRUE)
```

```{r}

mapview(ca_counties_withgeo, zcol = "medincomeE")

mylabel <- glue::glue("{ca_counties_withgeo$NAM} {ca_counties_withgeo$medincome}")

mapview(ca_counties_withgeo, zcol = "medincomeE", 
         alpha.regions = 1,
         label = mylabel)

```
