---
title: "Policy Review"
format: html
editor: visual
---

### [HOME](https://syoshiro.github.io/index) \| [PAST WORK](https://syoshiro.github.io/Past%20Work) \| [RESUME](https://github.com/syoshiro/syoshiro.github.io/blob/main/Sarina%20Oshiro%20Resume%202024.pdf)

\

Below, please find a copy of a policy analysis review paper completed in December of 2022.

#### **Beyond the Gridlock: Renewable Portfolio Standards and the Future of Clean Energy in the United States**

1\. CLIMATE CHANGE AND ENERGY PRODUCTION

Anthropogenic climate change is the crisis of our time. The global average temperature has already risen more than 1º C above pre-industrial levels as human processes release exorbitant amounts of carbon dioxide, methane, and other "greenhouse gasses" into the atmosphere (Lindsey & Dahlman, 2022). A recent report from the UN Intergovernmental Panel on Climate Change (IPCC) found that "stronger heat waves, longer droughts, more frequent floods, accelerating sea level rise and storm surges" caused by climate change are already impacting millions and will only intensify over time (IPCC, 2022, p. 176). These risks are especially dire for the poor or disadvantaged, who may not have equal access to healthcare, information about climate-driven natural disasters, adequate air cooling or heating systems, or ability to move in case of disaster (Climate Change and Health Equity, 2022). But while the wealthy can insulate themselves from climate threats, the problem poses a direct threat to the entire global economic system upon which they rely. Many industries including agriculture, forestry, fisheries, and tourism are highly susceptible to warmer temperature, rising seas, and extreme weather (Cho, 2019). Though hard to measure, some estimates put the cost of just 2.8ºC of warming at nearly 300 billion dollars to the US economy alone; the total global cost would be astounding (Cho, 2019). In order to limit increasing risks and get on the necessary path to a zero carbon society by 2050, "we must aim to cut our emissions in half" within this decade (Stokes, 2020, p. 12). Unfortunately, as of 2022, the IPCC found "negligible evidence that existing responses are adequate to reduce climate risk" (p. 2415). We are on the wrong track, but where should we look for answers? 

The role of the US in contributing to the climate crisis and its potential role in solving it cannot be understated. In 2019, out of the 33,621.5 million metric tons of global carbon dioxide emissions, the US contributed 5,130 million metric tons, or about 15% (U.S. Department of the Interior, n.d.). While other countries like China may emit a higher net total of carbon, there is no doubt the United States is one of the single most responsible parties to climate change, especially considering historic emissions. Within the U.S, about 32% of total emissions comes from electricity generation (Environmental Protection Agency, 2022). Electricity, of course, is fundamental to almost every aspect of industrialized modern life; and, it will actually need to grow in the coming years to support the electrification of transportation, buildings, and industry (Stokes, 2020, p. 13). Despite this fact, as of 2018, only 17% of power in the U.S. was generated from renewable energy sources like wind, solar, geothermal, biofuel, and hydropower (Stokes, 2020, p. 13). Because of the technological and economic influence of the U.S., along with the sheer amount of carbon emitted, finding the best ways to efficiently and rapidly scale renewable energy production nationwide is "the first linchpin" to solving the climate crisis on a global scale (Stokes, 2020, p. 13). 

Regulatory control over electricity in the U.S., however, is complicated. The Federal Power Act of 1935 gives jurisdiction over "sales from electricity generators to the utilities that own the transmission and distribution grid" to the federal government, while it gives jurisdiction over "retail sales" from the utilities to "end-use consumers" to the states (Welton, 2018, p. 1077). Natural monopolies for energy production existed throughout the 20th century, but deregulatory movements in the 1990s led to a transition to competitive electricity markets (Welton, 2018, p. 1079). In an attempt to bring regulatory balance back, the Federal Energy Regulatory Commission (FERC) created "electricity-management organizations" called  Regional Transmission Organizations (RTOs) or Independent System Operators (ISOs), which some states opted in to and some states did not (Welton, 2018, p. 1079). This resulting mix has left some states with absolute regulatory control over their in-state energy supply and others with control that is partially contested and interconnected with out of state sources; but on the whole, state governments nationwide have the most practical control over electricity and the strongest capacity to drive renewable energy growth. This is especially clear when considering the paralyzing gridlock and considerable absence of action on climate change at the federal level. 

\

2\. VARIATION IN CARBON EMISSIONS AND CLEAN ENERGY PRODUCTION 

On a state-by-state level, carbon emissions related to electricity production vary greatly. According to 2020 data from the U.S. Energy Information Administration (EIA), the state with the highest energy-related carbon dioxide emission by net total is Texas, at a whopping 624 million metric tons (Mt), followed by California at 303.4 Mt; this is largely due to population size and sprawl. Using a more revealing measure, the state with the highest per-capita energy-related carbon emission was Wyoming with 96.4 Mt (U.S. Energy Information Administration, 2020). Compare this to the District of Columbia, which saw a per-capita emission total of just 3.5 Mt (U.S. Energy Information Administration, 2020). Joining Wyoming in the top five for per-capita carbon emissions in 2020 were North Dakota, Alaska, West Virginia, and Louisiana (U.S. Energy Information Administration, 2020). Critically, Alaska and Mississippi were the only two states to see a rise in per-capita energy-related emissions; while other states are generally decarbonizing (albeit at vastly different rates), Alaska and Mississippi are on track to emit even more carbon to power their grids in the coming years (U.S. Energy Information Administration, 2020). In terms of clean energy production, Kentucky (0.7%), Tennessee (1.7%), Louisiana (2.2%), Pennsylvania (2.4%), and Arkansas (2.5%) have the smallest proportions of renewable energy in their total mix while Iowa has the highest proportion at 62.5% (U.S. Energy Information Administration, 2020). 

Although industry and geographic factors (such as extreme cold weather, which demands higher energy for heat) play a role, the wide range of energy policies in each of these states significantly contributes to the variety in emissions and renewable energy production. Though complex, the adoption of these policies is driven by two central political variables: intensity of fossil fuel interest group mobilization and the partisan lean of the general electorate.

Stokes (2020) conducted an extensive examination of the role interest groups have played in the adoption of certain climate-related energy policies. In the 1990s, there was actually a general bipartisan consensus around climate change and a desire to move towards clean energy. During that time, emerging renewable energy advocacy networks pushed policies that encouraged the development of renewables, finding early success in states like California, Texas, Massachusetts, Arizona, and Kansas (Stokes, 2020, p. 6). But after this initial wave of clean energy and decarbonization policy adoption, fossil fuel interests began to coalesce and organize in opposition of new policy proposals; pulling from deep pockets, they put a concerted effort towards softening or completely reversing standards already in place (Stokes, 2020, p. 6-7). To do so, these interest groups engaged in both direct and indirect oppositional action. With substantial political power and funding relative to advocates, fossil fuel interest groups have wielded influence over individual politicians and bureaucrats via direct lobbying, leveraging relationships, campaign contributions, and supplying information (Stokes, 2020, p. 61). The latter avenue of information is particularly important in the climate space; conservative, fossil fuel-aligned interest groups like the the American Legislative Exchange Council (ALEC) "created model bills designed to repeal RPS and net metering laws", both of which were central to the initial movement on clean energy (Stokes, 2020, p. 229). Indirect methods of influence generally involve "targeting the parties, the public, and the courts to undermine policy" (Stokes, 2020, p. 63). Fossil fuel interests commonly rely on false political ads and other forms of propaganda to capture the support of the public (Stokes, 2020, p. 66). This included "\[ratcheting\] up their efforts to deny climate science as part of their campaign to block climate policy" (Stokes, 2020, p. 9). Even when they fail to drum up enough public support, fossil fuel groups have also been known to stage fake protests, also called "astroturfing", in an attempt to manipulate politicians into believing anti-clean energy positions are wildly popular (Stokes, 2020, p. 66). As a result, "despite more than 40 years of effort from advocates, clean energy laws across the United States have barely shifted the needle" and fossil fuel interests have reaped the financial benefits of dangerously high emissions (Stokes, 2020, p. 11).

In addition to the strength and connectivity of interest groups, the partisan lean of the electorate is also an important political indicator of climate policies in a given state. Although earlier evidence is mixed, in part because of polarization over time, contemporary research has demonstrated a clear connection between a Republican majority in the electorate and weaker climate and clean energy policies. Simply put, in terms of policy strength, "blue states consistently trend higher than purple states -- and purple states consistently trend higher than red states" (Trachtman, 2020, p. 3). While the work of interest groups has certainly affected the political environment nationwide, fundamental partisan "ideological disagreements over the proper role of government intervention in the economy" also has a significant impact on Republicans' positive reception of anti-clean energy positions compared to Democrats (Hess et al., 2015, p. 11). Finally, it is important to note that strong clean energy policies are most reliant on the partisanship of the electorate, not on control of the state legislature by Democrats versus Republicans (Trachtman, 2020). Although a unified Democratic state government may be able to adopt clean energy mandates like Renewable Portfolio Standards (RPS) or significantly increase stringency of existing laws, these types of policies provide no significant incentive to deviate greatly from the average will of the voters. This explains why "a shift from divided to Democratic control of government is associated with between a 3- and 4-point increase in RPS strength", which is statistically significant but notably smaller compared to the 14-16 point increase in RPS strength when given a 10 point increase in Democratic voter majority (Trachtman, 2020, p. 5-6). Thus, Trachtman's (2020) findings suggest that "passing climate policy is not just about having Democrats in office, but also about the pressure that individuals and groups in a state are willing and able to put on their elected leaders" (p. 8).

\

3\. IDEAL SOLUTION: RENEWABLE PORTFOLIO STANDARDS 

Renewable Portfolio Standards (RPS), as mentioned briefly before, were a core policy in the initial push for clean energy in the 1990s and early 2000s. Generally, RPS is a "policy that requires retail suppliers of electricity (otherwise referred to as load-serving entities, or LSEs) to meet a specific portion of their energy supply needs with eligible forms of renewable energy" rather than fossil fuel sources like coal or natural gas (Wiser et al., 2004, p. 239). They are typically enforced via direct government regulation to check for compliance and consequent "penalties on those suppliers that fail to meet their renewable energy purchase obligations" (Wiser et al., 2004, p. 239). This type of policy was first adopted in Iowa in 1983, but spread to 29 states and Washington, D.C. by 2020 (Joshi, 2021, p. 4). These standards are usually enacted by vote of the state legislature, but have been enacted by ballot initiative in four cases (Pritchard & Mills, 2021, p. 2). States that are part of RTOs have typically acted independently to set RPS, but may be somewhat politically or legally constrained (Welton, 2018, p. 1117). Compared to other types of policies designed to decarbonize the US electrical grid, RPS has the benefit of being quite flexible in implementation and readily applicable to the political and policy needs of every state. By mandating targets but not outlining the specific actions energy suppliers must take, RPS creates "strong incentives for cost reduction" while still achieving decarbonization (Wiser et al., 2004, p. 239). 

It is important to realize, however, that not all RPS are created equal; in fact, there is a huge range of design across states with existing RPS. As part of the initial push in 2004, Arizona set their percentage purchase obligation to 1.1% while California pursued 20% (Wiser et al., 2004, p. 241). The variation in stringency has only grown in the years since, with each state tailoring their RPS to address the renewable resources they have available and to prioritize different goals, from electricity affordability to a rapid pace of decarbonization. 

Despite the differences in specific design, an extensive body of literature has found that RPS policies writ large are effective at reducing the proportion of fossil fuel-powered energy and promoting a greener grid. Joshi (2021) conducted a comprehensive review of the impacts of RPS across renewable sources nationwide. He found that RPS is especially impactful on wind and solar; with respect to the latter, "RPS driven change represents higher proportional growth in solar capacity... from 1990 to 2014" (Joshi, 2021, p. 15). As such, "RPS plays a critical role in the development of the renewable energy sector" (Joshi, 2021, p. 20). Furthermore, Joshi (2021) proves that RPS does actually "\[increase\] the proportion of aggregate renewable electricity capacity in total electricity capacity" rather than expanding alongside fossil fuel sources (p. 17). Carley, Davies, Spence, and Zirogannis (2018) also contribute findings on the effectiveness of RPS, focusing on the empirical impact of policy design differences and stringency. They find that level of stringency is significant, and that "\[states\] with stronger standards, all else being equal, tend to have more renewable energy development" (Carley et al., 2018, p. 761). The authors recognize that policy makers must make difficult, political trade-offs when adopting RPS. However, some concessions are actually detrimental to the efficacy of RPS and may explain the failure of some RPS states to substantially transition to renewables. For instance, RPS that "\[allow\] energy efficiency to count toward a mandate" are "associated with lower rates of renewable energy capacity." (Carley et al., 2018, p. 761). 

Based on evidence from the past two and a half decades, RPS is a highly effective policy solution to meet the challenge of decarbonization of the US electrical grid. States with RPS, especially strong ones, have statistically significantly higher proportions of renewable energy sources (Carley et al., 2018; Joshi, 2021). However, both partisanship and interest groups have stood in the way of further action, and have driven substantial retrenchment of these policies in some states; Carley et al. (2018) prove preventing scale-backs is critical. According to Hess, Mai, and Pride Brown (2015), climate change policies which involve mandates, such as RPS, have a considerable level of political opposition by Republican politicians. In their qualitative study of opinion, many Republican legislators expressed common conservative concerns that such government mandates were unnecessary and would "create unnecessary costs for consumers and businesses" (Hess et al., 2015, p. 25). For example, one Republican legislator from Utah said: "If you do it by tax credit, or make it optional, that is okay, but mandates don't play well up here" (Hess et al., 2015, p. 24). Compounded by increasing rates of polarization, this partisan opposition poses a difficult challenge to the political viability of RPS. Advocates may be more inclined to momentarily forgo RPS (despite its comprehensive efficacy) and instead push for policies such as solar tax credits, as the Legislator from Utah alludes to. These polices do have significantly higher support among Republicans, and have higher likelihood rates of being passed by state legislatures (Hess et al., 2015, p. 27). 

But some national polling data is a bit more mixed and may offer some hope for RPS. For one, in a 2015 survey, 74% of Americans agreed that "state governments should require a set portion of all electricity to come from renewable energy sources such as wind and solar power" (Mills et al., 2015, p. 1). In other words, a strong majority of voters support RPS. Furthermore, counter to the Republican and fossil-fuel interest group narrative that consumers/voters are against electricity cost increases RPS can incur, 58% of Americans said they would still support RPS if their energy bill went up by \$25 per year (Mills et al., 2015, p. 1). A Consumer Reports survey from 2018 supported this trend, finding that 76% of Americans "agree that increasing renewable energy is a worthwhile goal" (Farrell, 2018). Most recently, a 2022 Pew Research survey found that 69% of Americans "prioritize developing alternative energy sources" over fossil fuels; although this does represent a drop compared to the 2018 Consumer Reports poll, decarbonization of the energy system has retained remarkably high popularity (Schaeffer, 2022). 

\

4\. CONCLUSION 

It has never been more clear that climate action is urgently needed to prevent catastrophic changes; some of the damage is already here. A cornerstone piece of decreasing global carbon emissions is finding ways to turbocharge the decarbonization of the American energy production sector. Given the gridlock and partisanship that has taken hold of national politics along with regulatory jurisdiction of the energy grid, we must look to state governments for substantial action. One tried and true policy for reducing carbon emissions and increasing the proportion of renewable sources in a state's energy mix is known as RPS, or Renewable Portfolio Standards. However, partisanship of the electorate compounded by the concentrated efforts of powerful fossil-fuel interest groups has severely weakened and abolished many existing RPS laws and has prevented the adoption of new policies. In the short term absence of support in states with significant Republican electorates and active interest groups, advocates may need to consider prioritizing non-mandate policies such as solar tax credits. But, the tide may be shifting as the public becomes more aware of the risks of climate change and demand for renewable energy grows. Advocates should continue to look for opportunities to push new RPS or seriously strengthen existing RPS in order to maximize decarbonization effects and put a stop to this crisis. 

\
------\
\

**References**

Carley, S., Davies, L. L., Spence, D. B., & Zirogiannis, N. (2018). Empirical evaluation of the stringency and Design of Renewable Portfolio Standards. Nature Energy, 3(9), 754--763. https://doi.org/10.1038/s41560-018-0202-4

Cho, R. (2019, June 20). How climate change impacts the economy. Columbia Climate School. Retrieved December 16, 2022, from https://news.climate.columbia.edu/2019/06/20/climate-change-economy-impacts/

Climate Change and Health Equity. HHS.gov. (2022, May 6). Retrieved December 16, 2022, from https://www.hhs.gov/climate-change-health-equity-environmental-justice/climate-change-health-equity/index.html

Environmental Protection Agency. (2022, February 25). Global Greenhouse Gas Emissions Data. EPA. Retrieved December 16, 2022, from https://www.epa.gov/ghgemissions/global-greenhouse-gas-emissions-data

Farrell, M. H. J. (2018, October 29). Majority of Americans want cleaner energy from renewable sources. Consumer Reports. Retrieved December 16, 2022, from <https://www.consumerreports.org/alternative-energy/majority-of-americans-want-cleaner-energy-from-renewable-sources/>

\
\

IPCC. (2022). Climate Change 2022: Impacts, Adaptation and Vulnerability. Contribution of Working Group II to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change \[H.-O. Pörtner, D.C. Roberts, M. Tignor, E.S. Poloczanska, K. Mintenbeck, A. Alegría, M. Craig, S. Langsdorf, S. Löschke, V. Möller, A. Okem, B. Rama (eds.)\]. Cambridge University Press. Cambridge University Press, Cambridge, UK and New York, NY, USA, 3056 pp., doi:10.1017/9781009325844.

Joshi, J. (2021). Do renewable portfolio standards increase renewable energy capacity? evidence from the United States. Journal of Environmental Management, 287, 112261. https://doi.org/10.1016/j.jenvman.2021.112261

Lindsey, R., & Dahlman, L. A. (2022, June 28). Climate change: Global temperature. Climate.gov. Retrieved December 16, 2022, from https://www.climate.gov/news-features/understanding-climate/climate-change-global-temperature

Mills, S. B., Rabe, B. G., & Borick, C. (2015, June). Widespread public support for renewable energy mandates despite proposed rollbacks. Widespread Public Support for Renewable Energy Mandates Despite Proposed Rollbacks \| Center for Local, State, and Urban Policy. Retrieved December 16, 2022, from https://closup.umich.edu/issues-in-energy-and-environmental-policy/22/widespread-public-support-for-renewable-energy-mandates-despite-proposed-rollbacks

Pritchard, Z. D., & Mills, S. (2021). Renewable energy requirements on the ballot: An analysis of county-level voting results. Energy Policy, 148, 111949. https://doi.org/10.1016/j.enpol.2020.111949

Schaeffer, K. (2022, April 22). For earth day, key facts about Americans' views of climate change and Renewable Energy. Pew Research Center. Retrieved December 16, 2022, from https://www.pewresearch.org/fact-tank/2022/04/22/for-earth-day-key-facts-about-americans-views-of-climate-change-and-renewable-energy/

Stokes, L. C. (2020). Short circuiting policy: Interest Groups and the Battle Over Clean Energy and climate policy in the American States. Oxford Academic. Oxford university press. Retrieved December 16, 2022, from https://doi.org/10.1093/oso/9780190074258.003.0001.

Trachtman, S. (2020). What drives climate policy adoption in the U.S. states? Energy Policy, 138, 111214. https://doi.org/10.1016/j.enpol.2019.111214

U.S. Department of the Interior. (n.d.). How much carbon dioxide does the United States and the world emit each year from energy sources? USGS. Retrieved December 16, 2022, from https://www.usgs.gov/faqs/how-much-carbon-dioxide-does-united-states-and-world-emit-each-year-energy-sources

U.S. Energy Information Administration. (2020). Energy-Related CO2 Emission Data Tables. Retrieved December 16, 2022, from https://www.eia.gov/environment/emissions/state/. 

Wiser, R., Porter, K., & Grace, R. (2004). Evaluating experience with renewables portfolio standards in the United States - mitigation and adaptation strategies for Global Change. SpringerLink. Retrieved December 16, 2022, from https://link.springer.com/article/10.1007/s11027-005-6573-4 

\
